name: ci

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed
      - edited

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
